//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Structure_helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConnectionDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConnectionDB()
        {
            this.PipeEndDBs = new HashSet<PipeEndDB>();
            this.StructureDBs = new HashSet<StructureDB>();
        }
    
        public int Id { get; set; }
        public int UpperPipeEndId { get; set; }
        public int LowerPipeEndId { get; set; }
        public int UpperStructureId { get; set; }
        public int LowerStructureId { get; set; }
        public int JobId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PipeEndDB> PipeEndDBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StructureDB> StructureDBs { get; set; }
    }
}
