//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Structure_helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class PipeEndDB
    {
        public int Id { get; set; }
        public int StructureId { get; set; }
        public string Direction { get; set; }
        public Nullable<double> Invert { get; set; }
        public Nullable<int> Flow { get; set; }
        public Nullable<double> Diameter { get; set; }
        public string Type { get; set; }
        public Nullable<int> ConnectionId { get; set; }
        public int JobId { get; set; }
    
        public virtual ConnectionDB ConnectionDB { get; set; }
        public virtual StructureDB StructureDB { get; set; }
    }
}
