//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Structure_helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class StructureDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StructureDB()
        {
            this.PipeEndDBs = new HashSet<PipeEndDB>();
        }
    
        public int Id { get; set; }
        public string Shot { get; set; }
        public string Label { get; set; }
        public Nullable<double> Elevation { get; set; }
        public Nullable<double> Northing { get; set; }
        public Nullable<double> Easting { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public string Type { get; set; }
        public Nullable<int> ConnectionId { get; set; }
        public int JobId { get; set; }
    
        public virtual ConnectionDB ConnectionDB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PipeEndDB> PipeEndDBs { get; set; }
    }
}
